Highly sensitive spatial transcriptomics at near-cellular resolution with Slide-seqV2

ShortName: stickels2020highly

Steps of processing the data from raw to Anndata:

In [1]:
# 1, Download the raw data from https://singlecell.broadinstitute.org/single_cell/study/ SCP815/sensitive-spatial-genome-wide-expression-profiling-at-cellular-resolutio n#study-summary

In [ ]:
# this is the data released from slide-seqV2 original paper

In [ ]:
# file format:
#     BeadLocationsForR.csv
#     MappedDGEForR.csv.csv

In [1]:
# take one sample as an example

In [27]:
import scanpy as sc
import pandas as pd
import anndata as ad
data_path = ''
count_file = 'Cerebellum_MappedDGEForR.csv'
meta_file = 'Cerebellum_BeadLocationsForR.csv'
count0 = pd.read_csv(f'{data_path}/{count_file}')
meta = pd.read_csv(f'{data_path}/{meta_file}')

In [28]:
count0

,Row,CTTCCATGACATTT,TAGCCGGGTCTCTG,GCCTTGCTGAGCTC,AGATACCAAGCCTT,TGAAACGTGTCATT,CCGATTAAAGCGGT,CTGACGTTTTAGGA,ACTAACCTTCTCGA,GACTGTGGGGGCGA,...,ACGGTGTAGACAAA,TTTTTCAAGAAACA,AGGGTAACGAAAAC,TTGCCCGTCAAACA,CACCGACTCAGAAA,GACTCGAGCAAAAA,TCTACAAGCAAAAC,AAAAATAAAAAAAA,AAATAAAAAAAAAA,AAACAAAAAAAAAA
0,0610005C13Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0610007P14Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0610009B22Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0610009E02Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0610009L18Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23091,mt-Tv,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23092,n-R5-8s1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23093,n-R5s173,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23094,n-R5s48,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23095,n-R5s76,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [72]:
count=count0.values[:,1:].T

In [74]:
cell_id_array = count0.columns[1:]
cell_id_array

Index(['CTTCCATGACATTT', 'TAGCCGGGTCTCTG', 'GCCTTGCTGAGCTC', 'AGATACCAAGCCTT',
       'TGAAACGTGTCATT', 'CCGATTAAAGCGGT', 'CTGACGTTTTAGGA', 'ACTAACCTTCTCGA',
       'GACTGTGGGGGCGA', 'GCTCCGATCATAGG',
       ...
       'ACGGTGTAGACAAA', 'TTTTTCAAGAAACA', 'AGGGTAACGAAAAC', 'TTGCCCGTCAAACA',
       'CACCGACTCAGAAA', 'GACTCGAGCAAAAA', 'TCTACAAGCAAAAC', 'AAAAATAAAAAAAA',
       'AAATAAAAAAAAAA', 'AAACAAAAAAAAAA'],
      dtype='object', length=39496)

In [75]:
gene_id_array = count0['Row']
gene_id_array

0        0610005C13Rik
1        0610007P14Rik
2        0610009B22Rik
3        0610009E02Rik
4        0610009L18Rik
             ...
23091            mt-Tv
23092         n-R5-8s1
23093         n-R5s173
23094          n-R5s48
23095          n-R5s76
Name: Row, Length: 23096, dtype: object

In [76]:
count_X = count.astype('float')

In [77]:
adata = ad.AnnData(count_X)
adata.var_names = gene_id_array
adata.obs_names = cell_id_array

/tmp/ipykernel_68485/3501277586.py:2: FutureWarning: X.dtype being converted to np.float32 from float64. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  adata = ad.AnnData(count_X)

In [78]:
meta = pd.read_csv(f'{data_path}/{meta_file}')
meta

             barcodes       xcoord       ycoord
0      CTTCCATGACATTT  2892.276596  3060.489362
1      TAGCCGGGTCTCTG  5459.803030  4279.257576
2      GCCTTGCTGAGCTC  1632.575000  3463.375000
3      AGATACCAAGCCTT  3718.147059  3273.235294
4      TGAAACGTGTCATT  3733.886364  5466.000000
...               ...          ...          ...
39491  GACTCGAGCAAAAA  4214.606061  2584.696970
39492  TCTACAAGCAAAAC  4079.536082  4734.577320
39493  AAAAATAAAAAAAA  1279.972973   376.756757
39494  AAATAAAAAAAAAA   131.677419  1122.064516
39495  AAACAAAAAAAAAA  1007.896552  3779.942529

[39496 rows x 3 columns]

In [79]:
meta = meta.set_index('barcodes')

In [80]:
adata.obsm['spatial'] = meta.loc[adata.obs_names].loc[:,['xcoord','ycoord']]

In [81]:
adata

AnnData object with n_obs × n_vars = 39496 × 23096
    obsm: 'spatial'

In [ ]:
adata.write_h5ad(f'{data_path}/SCP948_cerebellum.h5ad')

In [ ]:
# index_colums =count0['Row']
# index_colums=list(index_colums)
# index_row=count0.columns[1:]
# index_row=list(index_row)
# len(index_colums)
# len(index_row)
# count = pd.DataFrame(count,columns=index_colums,index=index_row)
# index_row

In [65]:
count

,0610005C13Rik,0610007P14Rik,0610009B22Rik,0610009E02Rik,0610009L18Rik,0610009O20Rik,0610010F05Rik,0610010K14Rik,0610011F06Rik,0610012D04Rik,...,mt-Tp,mt-Tq,mt-Tr,mt-Ts2,mt-Tt,mt-Tv,n-R5-8s1,n-R5s173,n-R5s48,n-R5s76
CTTCCATGACATTT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TAGCCGGGTCTCTG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GCCTTGCTGAGCTC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AGATACCAAGCCTT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TGAAACGTGTCATT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GACTCGAGCAAAAA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TCTACAAGCAAAAC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAAAATAAAAAAAA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAATAAAAAAAAAA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAACAAAAAAAAAA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0